services:
  db:
    image: postgres:16
    container_name: goapi-db
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypass
      POSTGRES_DB: goapi
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: goapi
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: myuser
      DB_PASSWORD: mypass
      DB_NAME: goapi
    ports:
      - "8010:8010"
    # optional: wait for db to be ready before starting
    command: sh -c "sleep 5 && ./goapi"

volumes:
  db_data:
